# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# sys.path.insert(0, os.path.abspath('.'))
from recommonmark.parser import CommonMarkParser
from datetime import datetime
import os
import sys


# -- Project information -----------------------------------------------------

project = 'yiming.blog'
copyright = f'2020-{datetime.now().year}, Yiming Dai'
author = 'Yiming Dai'

# The full version, including alpha/beta/rc tags
version = '0.1'
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    "IPython.sphinxext.ipython_directive",
    "IPython.sphinxext.ipython_console_highlighting",
    "matplotlib.sphinxext.plot_directive",
    "nbsphinx",
    'sphinx_panels',
]

# Supporting Markdown
source_parsers = {
    '.md': CommonMarkParser,
}

# The suffix of source filenames.
source_suffix = ['.rst', '.md']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The encoding of source files.
source_encoding = "utf-8"

# The master toctree document.
master_doc = "index"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["**.ipynb_checkpoints", ".DS_Store", "Thumbs.db", ]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'pydata_sphinx_theme'

html_favicon = '_static/img/favicon.ico'

html_logo = '_static/img/logo.svg'

html_title = ''


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = [
    'css/custom.css',
]

# All configuration options are passed with the html_theme_options
# variable, a dictionary with key: val pairs that you can configure in various ways.
html_theme_options = {
    # 	"logo_link": "<other page or external link>",
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/dai-yiming",
            "icon": "fab fa-github",
        },
        {
            "name": "LinkedIn",
            "url": "https://www.linkedin.com/in/yimingdai/",
            "icon": "fab fa-linkedin",
        },
    ],
    "collapse_navigation": True,
    "navigation_depth": 2,
    "show_prev_next": False,
    "show_toc_level": 2,
    "navbar_align": "right",
    # The right in-page sidebar
    "page_sidebar_items": ["page-toc"],
    "footer_items": ["copyright"],
    "search_bar_text": "Search the docs ..",
}

# The left sidebar
html_sidebars = {
    "**": [
        "search-field",
        # "localtoc.html",
        "sidebar-nav-bs",
        # 'relations.html',
        # 'sourcelink.html',
        # "globaltoc.html",
        # "custom_sidebar.html"
    ]
}

header = f"""\
.. ipython:: python
   :suppress:

   import numpy as np
   import pandas as pd

   np.random.seed(20787239)
   np.set_printoptions(precision=4, suppress=True)
   pd.options.display.max_rows = 15
"""


html_context = {
    "header": header,
}
